vdr: Bump to 2.0.5

diff --git a/packages/setup/scripts/update-transponders b/packages/setup/scripts/update-transponders
--- a/packages/setup/scripts/update-transponders
+++ b/packages/setup/scripts/update-transponders
@@ -3,18 +3,13 @@
 . gettext.sh
 export TEXTDOMAIN=openpctv
 
+scan_trans () {
 url1="http://www.fastsatfinder.com/bin/DVBViewerTE_Satellite_Transponders.exe"
-url2="http://www.fastsatfinder.com/bin/Dreambox-Transponders.zip"
 echo "$(gettext "Download transponders for scan-s2")"
-wget $url1 -O /tmp/transponders.7z || (echo "$(gettext "Can't download,Please check your network settings")"; exit)
-echo "$(gettext "Download transponders for enigma2")"
-wget $url2 -O /tmp/dreambox.zip || (echo "$(gettext "Can't download,Please check your network settings")"; exit)
+wget -t 3 $url1 -O /tmp/transponders.7z || (echo "$(gettext "Can't download,Please check your network settings")"; exit)
 [ -d /tmp/transponders ] && rm -rf /tmp/transponders
 mkdir /tmp/transponders
 p7zip x /tmp/transponders.7z -o/tmp/transponders
-echo "$(gettext "Update /etc/enigma2/satellites.xml...")"
-unzip -o /tmp/dreambox.zip -d /etc/tuxbox
-[ -f /etc/tuxbox/satellites_extra.xml ] && sed -i '/<satellites>/ r /etc/tuxbox/satellites_extra.xml' /etc/tuxbox/satellites.xml
 [ ! -d /etc/vdr/plugins/transponders ] && mkdir -p /etc/vdr/plugins/transponders
 echo "$(gettext "update transponders for vdr-reelchannelscan")"
 [ ! -d /usr/share/transponders ] && mkdir -p /usr/share/transponders
@@ -24,7 +19,24 @@ for i in /tmp/transponders/*.ini; do
   j=$(grep "^2=.*[E|W]" $i | sed 's/2=/S/g')
   cp $i /etc/vdr/plugins/transponders/$j.tpl
   awk -F',|=' 'NR>=14{if($6=="DVB-S"){a="S1";}else{a="S2"};b=$2"000"; split($5,arr,""); split($5,arr,"");print a,b,$3,$4"000",arr[1]"/"arr[2],"AUTO",$7}' $i > /usr/share/transponders/$j.ini
-echo "$(gettext "Convert transponders data sheet:/usr/share/transponders/$j.ini")"
+  echo "$(gettext "Convert transponders data sheet:/usr/share/transponders/$j.ini")"
 done
-rm -rf /tmp/transponders.7z /tmp/dreambox.zip /tmp/transponders
+rm -rf /tmp/transponders.7z /tmp/transponders
 echo "$(gettext "Done!")"
+}
+
+enigma2_trans () {
+url2="http://www.fastsatfinder.com/bin/Dreambox-Transponders.zip"
+echo "$(gettext "Download transponders for enigma2")"
+wget -t 3 $url2 -O /tmp/dreambox.zip || (echo "$(gettext "Can't download,Please check your network settings")"; exit)
+echo "$(gettext "Update /etc/enigma2/satellites.xml...")"
+unzip -o /tmp/dreambox.zip -d /etc/tuxbox
+[ -f /etc/tuxbox/satellites_extra.xml ] && sed -i '/<satellites>/ r /etc/tuxbox/satellites_extra.xml' /etc/tuxbox/satellites.xml
+rm -rf /tmp/dreambox.zip
+echo "$(gettext "Done!")"
+}
+
+if dialog --yesno "$(gettext "Do you want to update the satellite transponders from fastsatfinder.com? If you do not update it, your transponder parameters may not be the latest.")" 7 60; then
+  [ -x /usr/bin/vdr ] && scan_trans
+  [ -x /usr/bin/enigma2 ] && enigma2_trans
+fi
